Take on using bash-scrict-mode

diff --git a/profile-running-jvm b/profile-running-jvm
--- a/profile-running-jvm
+++ b/profile-running-jvm
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+# https://github.com/olivergondza/bash-strict-mode
+set -euo pipefail
+trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 
 if [ "$#" -lt 1 ]; then
     echo >&2 "Usage: $0 <pid> [<duration>]"
@@ -21,8 +24,8 @@ settings="$dir/jfc/detailed"
 
 set -x
 
-jcmd $pid VM.unlock_commercial_features
-jcmd $pid JFR.start name="$name" settings="$settings" duration="$duration" filename="$out"
+jcmd "$pid" VM.unlock_commercial_features || true
+jcmd "$pid" JFR.start name="$name" settings="$settings" duration="$duration" filename="$out"
 
 set +x
 
diff --git a/profile-surefire-run b/profile-surefire-run
--- a/profile-surefire-run
+++ b/profile-surefire-run
@@ -1,11 +1,14 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# https://github.com/olivergondza/bash-strict-mode
+set -euo pipefail
+trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 
-if [ ! -z "$1" ]; then
-  profile="$1"
-else
+if [ "$#" -eq 0 ]; then
   profile="detailed"
+else
+  profile="$1"
 fi
 profile_path="${DIR}/jfc/${profile}"
 if [ ! -f "$profile_path" ]; then
